<a href="https://colab.research.google.com/github/venkey024/Numpy_Notes/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
  # installation numpy
! pip install numpy

In [ ]:
import numpy as np


In [ ]:
# central object is an array
# create an 1D array
a = np.array([1,3,4,5,2,9,4])
print(a)
print(type(a))
# check shape of this array
a.shape
# How can you check datatype of element in array
a.dtype
# what is diff b/w int32 and int64
#what is diff b/w float32 and float64
#how can we find the dimensionalitly of array
a.ndim


[1 3 4 5 2 9 4]
<class 'numpy.ndarray'>


dtype('int64')

In [ ]:
# how can i see of my array? # no.of eleemnts i an array
a.size

In [ ]:
# how can i see the size in bytes of each eleemnt in an array
a.itemsize

Essential methods in an array

In [ ]:
b  = np.array([1,2,3])
print(b[0])
b[0] = 5
print(b)

1
[5 2 3]


In [ ]:
# Do element wise math operation
b  = np.array([1,2,3])
c = b*np.array([1,2,3])
print(c)

[1 4 9]


Array vs List

In [ ]:
# array vs list
l = [1,2,3,4,5]
ar = np.array()


In [ ]:
# add item at the end of an array
# d. append(10) -- it rises an error
#print(d)
# there are ways to add the items in the array , but it creates essential creates a new array
# l2 = l+[11]
# print(l2)
l = [1,2,3,4,5]
ar = np.array()
a2 = ar+np.array([10])
print(a2)

In [ ]:
# vector addition :- addition the arrays with same size
# we cannot add the vectors of same size
a1 = [1,2,3] + np.array([4,3,2])
print(a1)

[5 5 5]


In [ ]:
# multiplication
m = np.array([2,3,4,5])
print(m*2)


[ 4  6  8 10]


In [ ]:
# modify each item in a list and store it in new list do multiplication with 2
l= [2,4,6,8,10]
new_l = [x*2 for x in l]
print(new_l)



[4, 8, 12, 16, 20]


In [ ]:
# print square of al
print(a1)
print(a1**2)

[5 5 5]
[25 25 25]


In [ ]:
# print of square root of a1
# print(a1**0.5)
# np.exp(a1)
np.tanh(a1)


array([0.9999092, 0.9999092, 0.9999092])

In [ ]:
# how to find log of 2 by using numpy
a = np.log(a1)
print(a)

[1.60943791 1.60943791 1.60943791]


In [ ]:
# dot products
a = np.array([1,2,3])
b = np.array([3,2,1])
# sum of the products of the corresponding entries
# multiply each corresponding and element thenn take the sum

# cumbersome way of lists
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
print(dot)



print(a*b)




10
[3 4 3]


In [ ]:
# same thing in numpy
dot = np.dot(a,b)
print(dot)

10


In [ ]:
# sstep by step procedure manually
c = a* b
print(c)
d = np.sum(c)
print(f'The sum is {d}')

[3 4 3]
The sum is 10


In [ ]:
dot = a.dot(b)
print(dot)

10


In [ ]:
dot = (a*b).sum()
print(dot)

10


In [ ]:
# in newer versions
dot = a @b
print(dot)

10


In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([7,4,5])
dot = a@b
print(dot)

30


Speed Test -- Array vs List

In [ ]:
from timeit import default_timer as timer
a = np.random.randn(1000)
b = np.random.randn(1000)
# print(a)
# print(b)
A = list(a)
B = list(b)
T = 1000
def dot1():
  dot = 0
  for i in range(len(A)):
    dot += A[i] * B[i]
  return dot
def dot2():
  return np.dot(a,b)

# calculate the timing
start = timer()
for t in range(T):
  dot1()
end = timer()
t1 = end - start

# for dot2
start = timer()
for t in range(T):
  dot2()
end = timer()
t2 = end - start

print('time with list',t1)
print('time with array',t2)

print("ratio",t1/t2)




time with list 0.22161105600002884
time with array 0.001382078000006004
ratio 160.34627278566487


Multidimensional array

In [ ]:
a = np.array([[1,2],[3,4]])
a.shape
a.dtype
a.ndim


2

In [ ]:
# access the element
print(a[0])    # ---[1,2]
# print the 5
print(a[1,1])

[1 2]
5


In [ ]:
# print the all rows in column 0
print(a[:,0])

[1 4]


In [ ]:
# print the all columns in row 0
print(a[0,:])

[1 2]


In [ ]:
# print all the rows in column 1
print(a[:,1])

[2 5]


In [ ]:
print(a[1,:])

[4 5]


In [ ]:
# Transpose ----> Rows are changed into columns and --coulmns are changed into rows
a.T

array([[1, 4],
       [2, 5]])

In [ ]:
print(a)

[[1 2]
 [3 4]]


In [ ]:
# matrix mmultiplication with dot
b = np.array([[3,4],[5,6]])
c = a.dot(b)

[[13 16]
 [29 36]]


In [ ]:
# Determiaent finding
# fin the det|c|

c = np.linalg.det(a)
print(c)



-2.0000000000000004


In [ ]:
# find the diagonal of a
c = np.diag(a)
print(c)

[1 4]


In [ ]:
# print the inverse of matrix a ?
c = np.linalg.inv(a)
print(c)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
# diagonal on a vector returns ...diagonal matrix(overloaded function)
c = np.diag([1,4])
print(c)

[[1 0]
 [0 4]]


Indexing,Slicing,boolean,indexing

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a.shape)
print(a.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2


In [ ]:
# print [1 5 9]
print(a[:,0])

[1 5 9]


In [ ]:
#
print(a[0:2,1:3])

[[2 3]
 [6 7]]


In [ ]:
# neagative index
print(a[-1,-1]) # -- -ve row from reverse direction "-1" and -ve column in last position

12


Boolean indexing

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# print the values "true" if it is greater than 2 else false
print(a>2)

# note: this will be a rank 1 array


[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
# i want values greater than 2
print(a[a>2])
print(a[a>2].ndim)

[3 4 5 6]
1


# please go through rank 1 of an array

In [ ]:
# use where
#np.where():- same size with modified values
b = np.where(a>2,a,-1) # --> where(condition,array,values to be passed)
print(b)

[[-1 -1]
 [ 3  4]
 [ 5  6]]


In [ ]:
# Fancy Indexing :- with this indexing we can access multiple indices at once
a = np.array([10,9,78,44,22,67])
b = a[[1,3,5]]
print(b)

[ 9 44 67]


In [ ]:
###************** Compute indices where the condition is true *************

a = np.array([[10,9],[78,44]])

even = np.argwhere(a % 2 == 0).flatten()
print(even)

[0 0 1 0 1 1]


Reshaping an array

In [ ]:
a = np.arange(1,7)
print(a)

[1 2 3 4 5 6]


In [ ]:
# -- coverts the 1D to multidimensional
c = a.reshape(2,3)
print(c)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#newax :- is used to create a new axix in the data [row,:col]
# it is required when model require the data to shaped in a certain in a manner
print(a.shape)

(6,)


In [ ]:
d = a[np.newaxis:,]  #[row(newaxis),:]
print(d)
print(d.shape)
print(d.ndim)

[1 2 3 4 5 6]
(6,)
1


In [ ]:
d = a[:,np.newaxis] # [row(default):,column(newaxis)]
print(d)
print(d.shape)
print(d.ndim)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)
2


#Concatenation in arrays

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
# combined this array into 1D
c = np.concatenate((a,b),axis = None)
print(c)
# axis = 0
d = np.concatenate((a,b), axis = 0)
print(d)

# axis = 1
e = np.concatenate((a,b), axis = 1)
print(e)

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
# add new column in to array :note ---> we have to transpose it
c = np.concatenate((a,b.T),axis = 1)
print(c)


[[1 2 5]
 [3 4 6]]


In [ ]:
# ***************************** hstack *******************************

# hstack :- stack of arrays in sequence horizentally(column wise) need a tuple
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.hstack((a,b))
print(c)
# np.concatenate((a,b),axis = None)
d = np.concatenate((a,b),axis = None)
print(d)



[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]


In [ ]:
#*********************** vstack *******************
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.vstack((a,b))
print(c)

[[1 2 3 4]
 [5 6 7 8]]


Broadcasting

In [ ]:
""" it is a powerful mechanism that allows numpy arrays to work with different shapes
 when performing the arithmatic operations """
import numpy as np
x = np.array([[1,2,3],[4,5,6],[10,11,12]])
y = np.array([1,0,1]) # add y to each row of x using broadcasting
z = x+y
print(z)


[[ 2  2  4]
 [ 5  5  7]
 [11 11 13]]


Function and axis

In [ ]:
a = np.array([[7,8,9,10,11,12,13],[17,18,19,20,21,22,23]])
print(a.sum()) #---- sum of all elements
print(a.sum(axis = 0))
print(a.sum(axis = 1))
print(a.mean(axis = 0))
print(a.mean(axis = 1))

210
[24 26 28 30 32 34 36]
[ 70 140]
[12. 13. 14. 15. 16. 17. 18.]
[10. 20.]


#Data types

In [ ]:
x = np.array([1,2])
print(x.dtype)

int64


In [ ]:
# let np choos datatype
x = np.array([1.0,2.0])
print(x.dtype)

In [ ]:
# force a datatype how many bits you want
x = np.array([1,2], dtype = np.int32)
print(x.dtype)

int32


In [ ]:
x = np.array([1,2], dtype = np.float32)
print(x.dtype)

float32


Copying

In [ ]:
a = np.array([1,2,3])
b = a    # only copies references
b[0] = 42
print(a)

[42  2  3]


In [ ]:
a = np.array([1,2,3])
b = a.copy() # actual copy
b[0] = 42
print(a)
print(b)

[1 2 3]
[42  2  3]


# Generative arrays

In [ ]:
# print zeroes matrix 2 rows and 3 columns
a = np.zeros((2,3))
print(a)
# specific  nuber of matrix in 3 rows and 3 columns
c = np.full((3,3),(5))
print(c)


[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
# print identity matrix
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# linspace -- to separate the given data in to specific numbers
# dividing the range of numbers into parts
f = np.linspace(0,10,5)
print(f)


[ 0.   2.5  5.   7.5 10. ]


#Random numbers

In [ ]:
# random numbers
a = np.random.random(10)  # uniform 0-1 distributed
print(a)

[0.32648723 0.47038421 0.42117084 0.70534071 0.45519231 0.84278196
 0.81125487 0.905247   0.5887928  0.48945147]


In [ ]:
a = np.random.random(3)
print(a)

[0.49885616 0.01530908 0.56010659]


In [ ]:
b = np.random.randn(3,2) # normal/gussian distribution, mean 0 and unit variance
                         #
print(b)

[[ 0.90319228 -0.27946389]
 [-0.51054251 -0.16456526]
 [ 0.75858842  1.99098152]]


In [ ]:
m = np.random.randn(1000)
print(m.mean(),c.var(),c.std())


-0.031068998862162942 0.0 0.0


In [ ]:
d = np.random.randn(10,3)
print(d)
print(d.mean())

[[ 0.37080891  0.70388268 -0.80761622]
 [ 0.93922324 -0.33890034  0.29488327]
 [ 0.24304063 -1.78204351 -0.96113863]
 [-1.87524071 -0.47111559  0.95810132]
 [ 0.25711439  1.23095637 -0.77998104]
 [-0.79258763 -1.42720969  0.75492524]
 [-0.81456784 -1.02350734 -0.52214778]
 [-1.29622247 -0.54998559  0.97001703]
 [-0.8780379   1.13068674 -2.54565485]
 [-0.47299983  0.73822499  0.0973373 ]]
-0.28832516172083406


In [ ]:
d = np.random.randint(3,10, size =(3,3))
print(d)

[[6 3 7]
 [9 8 3]
 [9 4 7]]


In [ ]:
#*********************with integer between 0 upto integer exclusive
f = np.random.choice(10,size = 8)
print(f)

[8 7 8 6 4 2 6 5]


In [ ]:
a = np.random.randint(10,50,size = 1)
print(a)

[26]


In [ ]:
f = np.random.choice([1,2,3,4,5,6], size = 1)
print(f)

[6]


In [ ]:
a = np.array([1, 2, 3, 4, 5])
random_sample = np.random.choice(a, size=3, replace=False)
print(random_sample)

[1 2 5]


# linear Algebra(Eigen value/solving linear systems)

In [ ]:
a = np.array([[1,2],[3,4]])
eigenvalues, eigenvectors = np.linalg.eig(a)
print(eigenvalues)
print(eigenvectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
print(eigenvectors[:,0])

[-0.82456484  0.56576746]


In [ ]:
# how can we verify the eigenvalues and eigen vectors
#) e-vec  * e-val = a * e-vector
d = eigenvectors[:,0] * eigenvalues[0]
e = a @ eigenvectors[:,0]
print(d)
print(e)
print(d == e)
# correct way to compare matrix
print(np.allclose(d,e))

[ 0.30697009 -0.21062466]
[ 0.30697009 -0.21062466]
[ True False]
True


In [ ]:
m = np.array([[1,2,3],[4,5,6]])
n = np.array([[1,2,3],[4,5,6]])
print(np.allclose(m,n))


True


In [ ]:
# solving the linear systems
# x1 + x2 = 2200
# 1.5 x1  + 4 x2 = 5050
A = np.array([[1,1],[1.5,4]])
B = np.array([2200,5050])
# formula --> Ax = B <=> x = A- 1 B

# *****  1st method ******

# solving inverse is slow and less accurate
x = np.linalg.inv(A).dot(B)
print(x)

# ***** 2nd method
y = np.linalg.solve(A,B)
print(y)

[1500.  700.]
[1500.  700.]


# loading a csv file using numpy

In [ ]:
# load it with np.loadtxt
data = np.loadtxt("/content/sample_data/california_housing_train.csv" ,delimiter = ",",dtype = str)
print(data.shape,data.dtype)


(17001, 9) <U20


In [ ]:
data = np.genfromtxt("/content/sample_data/california_housing_train.csv" ,delimiter = ",",dtype = str)
print(data.shape,data.dtype)

(17001, 9) <U20


In [ ]:
a = np.array([[0,1],[1,0]])
m = np.tile(a,(4,4))
print(m)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
